### ISSUE TITLE
How to create VolumeSnapshot from disk volume id

### ISSUE THREAD

**Issue by huntkalio** [kubernetes-sigs/alibaba-cloud-csi-driver#1166]
I wan't to create VolumeSnapshot  from disk volumeHandle id, but faild with "Failed to check and update snapshot content: failed to take snapshot of the volume, d-xxxxxxxxxxx: "cannot create snapshot. Snapshot content
      kafka-test-content not bound to a snapshot"
Does Dynamic Snapshot support from disk id (not pvc)?

```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: kafka-test-content
spec:
  deletionPolicy: Delete
  driver: diskplugin.csi.alibabacloud.com
  source:
    volumeHandle: d-xxxxxxxxxxxxxxxxxx
  volumeSnapshotClassName: aliyun-csi-cloud-disk-snapshot
  volumeSnapshotRef:
    name: kafka-test-snapshot
    namespace: default
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: kafka-test-snapshot
  namespace: default
spec:
  source:
    volumeSnapshotContentName: kafka-test-content
```
