### ISSUE TITLE
LVM本地盘模式下，限制PV分配到某些节点

### ISSUE THREAD

**Issue by huiwq1990** [kubernetes-sigs/alibaba-cloud-csi-driver#200]
如果集群有三个节点，其中有一个节点A是没有可用的数据盘，期望使用本地盘的pod不会调度到这个节点。经过测试，现有功能是不支持这个功能的。
后来想到对节点A打标签，结合StorageClass的allowedTopologies实现。
具体实现方式

### 1 修改lvm的nodeserver，默认给节点加上DbKind标签
```
func (ns *nodeServer) NodeGetInfo(ctx context.Context, req *csi.NodeGetInfoRequest) (*csi.NodeGetInfoResponse, error) {
	return &csi.NodeGetInfoResponse{
		NodeId: ns.nodeID,
		// make sure that the driver works on this particular node only
		AccessibleTopology: &csi.Topology{
			Segments: map[string]string{
				TopologyNodeKey: ns.nodeID,
				"DbKind": "Mysql",
			},
		},
	}, nil
}
```
### 2 修改provisioner
如果不修改provisioner，计算拓扑的时候会出问题。报错内容如下：
```
topology map[DbKind:Mysql topology.lvmplugin.csi.alibabacloud.com/hostname:k8s-node-vmsdfp-9zb7i00u8q] from selected node "k8s-node-vmsdfp-9zb7i00u8q" is not in requisite: [map[DbKind:Mysql]]
```
我理解的意思是storageclass要求使用的拓扑是DbKind:Mysql，但是调度给出的拓扑是DbKind:Mysql topology.lvmplugin.csi.alibabacloud.com/hostname:k8s-node-vmsdfp-9zb7i00u8q。
实现方式是把topology.go的GenerateAccessibilityRequirements改了
![image](https://user-images.githubusercontent.com/4555057/75782414-dd283280-5d99-11ea-9750-b59dfc631dd8.png)

### 3 使用方式
对不希望调度的节点，取消DbType标签。
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-lvm-toplogy
provisioner: lvmplugin.csi.alibabacloud.com
parameters:
  vgName: vgcsi3
  pvType: localdisk
  fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: DbKind
    values:
    - Mysql
```

最后，测试sc工作符合预期，请问这么改对吗？还有更好的实现机制吗？多谢指点。
