### ISSUE TITLE
nas not support nodeAffinity

### ISSUE THREAD

**Issue by wusphinx** [kubernetes-sigs/alibaba-cloud-csi-driver#227]
1. my k8s is in hybrid cloud environment (1 node in aliyun ecs, and 4 private node, through high-speed channel to open both sides of the network)
2. apply `StorageClass` by `examples/nas/dynamic/sc-filesystem.yaml` which `StorageClass` is called `alicloud-nas-fs` When I create a statefulset with volumeClaimTemplates, I will expect the pod will schedule to node in aliyun ecs only, but  It is scheduled to my private node
3. Compare with `cloud_efficiency`,  I found the pv created by `cloud_efficiency` has `nodeAffinity` eg 
```
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.diskplugin.csi.alibabacloud.com/zone
          operator: In
          values:
          - cn-hangzhou-g
```

but I can't find `nodeAffinity` in pv created by `alicloud-nas-fs`.
So, I think the `alicloud-nas-fs` should have the same `nodeAffinity` with `cloud_efficiency`.
Maybe I can config it, but I don't know how to do.
Besides, where is source code of image `registry.cn-hangzhou.aliyuncs.com/acs/csi-provisioner:v1.2.2-aliyun`?
