### ISSUE TITLE
NAS driver crashed when provisioning a block volume

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-sigs/alibaba-cloud-csi-driver#498]
I tried to create a block volume using the NAS provisioner and the driver crashed. It should not crash, it must return an error that block volumes are not supported.

```
time="2021-08-10T00:48:31+08:00" level=info msg="CreateVolume: Starting NFS CreateVolume, nas-955a70f0-1200-4c0c-bff4-a04a6ec2931d, name:\"nas-955a70f0-1200-4c0c-bff4-a04a6ec2931d\" capacity_range:<required_bytes:1073741824 > volume_capabilities:<block:<> access_mode:<mode:SINGLE_NODE_WRITER > > parameters:<key:\"archiveOnDelete\" value:\"false\" > parameters:<key:\"server\" value:\"112b624b359-ndi10.eu-central-1.nas.aliyuncs.com\" > parameters:<key:\"volumeAs\" value:\"subpath\" > "
panic: interface conversion: csi.isVolumeCapability_AccessType is *csi.VolumeCapability_Block, not *csi.VolumeCapability_Mount
goroutine 95 [running]:
github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pkg/nas.(*controllerServer).CreateVolume(0xc0006c2840, 0x234e9a0, 0xc00090bd10, 0xc00031e7e0, 0xc0006c2840, 0x1, 0xc00075d2a0)
        /home/regressionTest/go/src/github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pkg/nas/controllerserver.go:185 +0x6479
github.com/container-storage-interface/spec/lib/go/csi._Controller_CreateVolume_Handler.func1(0x234e9a0, 0xc00090bd10, 0x1f22ae0, 0xc00031e7e0, 0x18, 0xc00075d280, 0x7f7fa0e4d3a8, 0x30)
        /home/regressionTest/go/pkg/mod/github.com/container-storage-interface/spec@v1.1.0/lib/go/csi/csi.pb.go:4947 +0x89
github.com/kubernetes-csi/drivers/pkg/csi-common.logGRPC(0x234e9a0, 0xc00090bd10, 0x1f22ae0, 0xc00031e7e0, 0xc00075d1e0, 0xc00075d280, 0xc0001b6b78, 0x508cc6, 0x1eb95a0, 0xc00090bd10)
        /home/regressionTest/go/pkg/mod/github.com/kubernetes-csi/drivers@v1.0.2/pkg/csi-common/utils.go:99 +0x15d
github.com/container-storage-interface/spec/lib/go/csi._Controller_CreateVolume_Handler(0x1efb880, 0xc0006c2840, 0x234e9a0, 0xc00090bd10, 0xc0008ff740, 0x218d300, 0x234e9a0, 0xc00090bd10, 0xc0003da210, 0xa4)
        /home/regressionTest/go/pkg/mod/github.com/container-storage-interface/spec@v1.1.0/lib/go/csi/csi.pb.go:4949 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00012d800, 0x236c7c0, 0xc00090ec00, 0xc0000c0e00, 0xc00068ec60, 0x3546800, 0x0, 0x0, 0x0)
        /home/regressionTest/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1024 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc00012d800, 0x236c7c0, 0xc00090ec00, 0xc0000c0e00, 0x0)
        /home/regressionTest/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1313 +0xd34
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00066c1c0, 0xc00012d800, 0x236c7c0, 0xc00090ec00, 0xc0000c0e00)
        /home/regressionTest/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:722 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
```

StorageClass:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
provisioner: nasplugin.csi.alibabacloud.com
metadata:
  name: alicloud-nas-subpath
mountOptions:
- nolock,tcp,noresvport
- vers=3
parameters:
  volumeAs: subpath
  server: "*censored*"
  archiveOnDelete: "false"
```

PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    annotations:
      volume.beta.kubernetes.io/storage-provisioner: nasplugin.csi.alibabacloud.com
    name: nasplugin.csi.alibabacloud.comhbzz5
spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: alicloud-nas-subpath
    volumeMode: Block
```
