### ISSUE TITLE
disk 不支持自定义 kubelet  --root-dir 

### ISSUE THREAD

**Issue by wangzhuzhen** [kubernetes-sigs/alibaba-cloud-csi-driver#561]
实际 kubelet 自定义的 root-dir 为 /data/kubelet,对应配置 disk-plugin.yaml 文件中 Pod 的 volumes 部分的只能如果如下定义，csi-plugin 无法运行

```yaml
- name: registration-dir
  hostPath:
    path: /data/kubelet/plugins_registry
    type: DirectoryOrCreate
- name: kubelet-dir
  hostPath:
    path: /data/kubelet
    type: Directory
```

原因是 disk-driver-registrar 容器无法启动，错误核心日志是 ”Registration process failed with error: RegisterPlugin error -- plugin registration failed with err: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/csi-plugins/diskplugin.csi.alibabacloud.com/csi.sock: connect: connection refused", restarting registration container.“

由于 disk-driver-registrar 无代码可参考，无法进一步查询，CSI 钉钉群也无人回答此问题。

 Pod 的 volumes 部分修改为 如下，则 csi-plugin  pod 正常运行：

```yaml
- name: registration-dir
  hostPath:
    path: /data/kubelet/plugins_registry
    type: DirectoryOrCreate
- name: kubelet-dir
  hostPath:
    path: /var/lib/kubelet
    type: Directory
```

但会导致一个问题：卷不能正常挂载到容器。看起来 pvc 和 Pod 都正常，但不能往容器中的挂载目录写数据，一写数据 Pod 就无法删除或者无法迁移重建。问题现象是：
* 【问题现象一】【必现】Pod 无法删除，一直 Terminating
* 【问题现象二】【极高概率出现】Pod 无法在其他节点创建成功，因为卷无法快速从当前节点随 Pod 迁移

通过分析kubelet 和 csi 插件disk 部分的代码，结合手动验证发现问题是原因是：上述Pod  volumes 配置情况下，csi-plugin 不能将卷挂载到宿主机的根 mount namespace 导致，这应该是  csi-plugin 部署时  registration-dir 对应的宿主机目录（/data/kubelet/plugins_registry）与 kubelet-dir 对应的宿主机目录（/var/lib/kubelet）没有层级关系，导致挂载传播不生效引起。

**Comment by mowangdk** [comment]
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-plugin
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: csi-plugin
  template:
    metadata:
      labels:
        app: csi-plugin
    spec:
      containers:
      - args:
        - --v=5
        - --csi-address=/home/t4/kubernetes/lib/kubelet/csi-plugins/diskplugin.csi.alibabacloud.com/csi.sock
        - --kubelet-registration-path=/home/t4/kubernetes/lib/kubelet/csi-plugins/diskplugin.csi.alibabacloud.com/csi.sock
        image: csi-node-driver-registrar:v1.2.0
        imagePullPolicy: IfNotPresent
        name: disk-driver-registrar
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/t4/kubernetes/lib/kubelet/
          mountPropagation: HostToContainer
          name: kubelet-dir
        - mountPath: /registration
          name: registration-dir
      - args:
        - --endpoint=$(CSI_ENDPOINT)
        - --v=5
        - --driver=disk
        - --basedir=/home/t4/kubernetes/lib
        - --nodeid=$(KUBE_NODE_NAME)
        env:
        - name: CSI_ENDPOINT
          value: unix://home/t4/kubernetes/lib/kubelet/csi-plugins/driverplugin.csi.alibabacloud.com-replace/csi.sock
        - name: SERVICE_TYPE
          value: plugin
        - name: MAX_VOLUMES_PERNODE
          value: "15"
        - name: KUBERNETES_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              key: address
              name: apiserver-info
        - name: KUBERNETES_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              key: port
              name: apiserver-info
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: csi-plugin
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: 11260
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: csi-plugin
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/t4/kubernetes/lib/kubelet
          mountPropagation: Bidirectional
          name: kubelet-dir
        - mountPath: /home/t4/kubernetes/lib/container
          mountPropagation: Bidirectional
          name: container-dir
        - mountPath: /dev
          mountPropagation: HostToContainer
          name: host-dev
        - mountPath: /var/log/
          mountPropagation: HostToContainer
          name: host-log
        - mountPath: /host/etc
          mountPropagation: HostToContainer
          name: host-etc
        - mountPath: /var/run/node-extender-server
          name: servicesocket
        - mountPath: /host/sys
          name: host-sys
        - mountPath: /host/dev/mem
          name: host-mem
        - mountPath: /var/addon
          name: asi-csi-token
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      hostPID: true
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: kube-scheduler
      securityContext: {}
      serviceAccount: alicloud-csi-plugin
      serviceAccountName: alicloud-csi-plugin
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /home/t4/kubernetes/lib/kubelet/plugins_registry
          type: DirectoryOrCreate
        name: registration-dir
      - hostPath:
          path: /home/t4/kubernetes/lib
          type: DirectoryOrCreate
        name: container-dir
      - hostPath:
          path: /home/t4/kubernetes/lib/kubelet
          type: Directory
        name: kubelet-dir
      - hostPath:
          path: /dev
          type: ""
        name: host-dev
      - hostPath:
          path: /var/log/
          type: ""
        name: host-log
      - hostPath:
          path: /sys/
          type: ""
        name: host-sys
      - hostPath:
          path: /etc
          type: ""
        name: host-etc
      - hostPath:
          path: /dev/mem
          type: ""
        name: host-mem
      - hostPath:
          path: /var/run/node-extender-server
          type: DirectoryOrCreate
        name: servicesocket
      - configMap:
          defaultMode: 420
          name: asi-csi-token
        name: asi-csi-token
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 5
    type: RollingUpdate
```

参考下上面这个yaml 改一下 kubelet rootpath 呢？
