### ISSUE TITLE
[nasplugin.csi] Persistence Volume Claim never bound if server parameter contain path

### ISSUE THREAD

**Issue by jtzell** [kubernetes-sigs/alibaba-cloud-csi-driver#569]
For example,

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ehrell-fs-jtg-nas-gp-retain
mountOptions:
  - vers=3
  - timeo=600
  - retrans=2
  - nolock,tcp,noresvport,hard
parameters:
  # optional. Default as 'subpath'; 
  # specify the provision type: 
  # 'subpath' means the provision volume use subpath of exist nfs filesystem as target. 
  # And 'filesystem' means the provision volume use new created nfs filesystem as target.
  volumeAs: subpath
  server: "768ea4b708-hry86.ap-southeast-1.nas.aliyuncs.com:/fs/jtg"
  # Optional. decide how to process removal path, if reclaimPolicy defined as delete. 
  # If set 'true', the removal path will be archived and not removed really, 
  # and if set 'false', the removal path will be removed when pv is deleted.
  archiveOnDelete: "false"
provisioner: nasplugin.csi.alibabacloud.com
reclaimPolicy: Retain
allowVolumeExpansion: true
```

With the above config, PVC that use the storage class is never bound!
