### ISSUE TITLE
云盘无法挂载 Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[kube-api-access-qb2bl data]: timed out waiting for the condition

### ISSUE THREAD

**Issue by huangzx3** [kubernetes-sigs/alibaba-cloud-csi-driver#582]
- disk-plugin.yaml
```
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: diskplugin.csi.alibabacloud.com
spec:
  attachRequired: true
  podInfoOnMount: true
---
  kind: DaemonSet
  apiVersion: apps/v1
  metadata:
    name: csi-plugin
    namespace: kube-system
  spec:
    selector:
      matchLabels:
        app: csi-plugin
    template:
      metadata:
        labels:
          app: csi-plugin
      spec:
        tolerations:
          - operator: Exists
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: type
                  operator: NotIn
                  values:
                  - virtual-kubelet
        nodeSelector:
          kubernetes.io/os: linux
        serviceAccount: csi-admin
        priorityClassName: system-node-critical
        hostNetwork: true
        hostPID: true
        containers:
          - name: disk-driver-registrar
            image: registry.cn-hangzhou.aliyuncs.com/acs/csi-node-driver-registrar:v1.2.0
            imagePullPolicy: Always
            args:
              - "--v=5"
              - "--csi-address=/var/lib/kubelet/csi-plugins/diskplugin.csi.alibabacloud.com/csi.sock"
              - "--kubelet-registration-path=/var/lib/kubelet/csi-plugins/diskplugin.csi.alibabacloud.com/csi.sock"
            volumeMounts:
              - name: kubelet-dir
                mountPath: /var/lib/kubelet
              - name: registration-dir
                mountPath: /registration
          - name: csi-plugin
            securityContext:
              privileged: true
              capabilities:
                add: ["SYS_ADMIN"]
              allowPrivilegeEscalation: true
            image: registry.cn-hangzhou.aliyuncs.com/acs/csi-plugin:v1.16.9.43-f36bb540-aliyun
            imagePullPolicy: "Always"
            args:
              - "--endpoint=$(CSI_ENDPOINT)"
              - "--v=2"
              - "--driver=disk"
            env:
              - name: KUBE_NODE_NAME
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: spec.nodeName
              - name: CSI_ENDPOINT
                value: unix://var/lib/kubelet/csi-plugins/driverplugin.csi.alibabacloud.com-replace/csi.sock
              - name: MAX_VOLUMES_PERNODE
                value: "15"
              - name: SERVICE_TYPE
                value: "plugin"
              - name: ACCESS_KEY_ID
                value: "LTAIhXXXXXXXXXX"
              - name: ACCESS_KEY_SECRET
                value: "IKL1FbnXRXXXXXXXXXXXXXXX"

            livenessProbe:
              httpGet:
                path: /healthz
                port: healthz
                scheme: HTTP
              initialDelaySeconds: 10
              periodSeconds: 30
              timeoutSeconds: 5
              failureThreshold: 5
            ports:
              - name: healthz
                containerPort: 11260
                protocol: TCP
            volumeMounts:
              - name: kubelet-dir
                mountPath: /var/lib/kubelet/
                mountPropagation: "Bidirectional"
              - name: etc
                mountPath: /host/etc
              - name: host-log
                mountPath: /var/log/
              - name: container-dir
                mountPath: /var/lib/container
                mountPropagation: "Bidirectional"
              - name: host-dev
                mountPath: /dev
                mountPropagation: "HostToContainer"
        volumes:
          - name: registration-dir
            hostPath:
              path: /var/lib/kubelet/plugins_registry
              type: DirectoryOrCreate
          - name: container-dir
            hostPath:
              path: /var/lib/container
              type: DirectoryOrCreate
          - name: kubelet-dir
            hostPath:
              path: /var/lib/kubelet
              type: Directory
          - name: host-dev
            hostPath:
              path: /dev
          - name: host-log
            hostPath:
              path: /var/log/
          - name: etc
            hostPath:
              path: /etc
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 10%
      type: RollingUpdate 
```

- disk-provisioner.yaml
```
kind: Service
apiVersion: v1
metadata:
  name: csi-provisioner
  namespace: kube-system
  labels:
    app: csi-provisioner
spec:
  selector:
    app: csi-provisioner
  ports:
    - name: dummy
      port: 12345
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-provisioner
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-provisioner
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-provisioner
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - csi-provisioner
              topologyKey: "kubernetes.io/hostname"
      tolerations:
      - effect: NoSchedule
        operator: Exists
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        operator: Exists
        key: node.cloudprovider.kubernetes.io/uninitialized
      priorityClassName: system-node-critical
      serviceAccount: csi-admin
      hostNetwork: true
      containers:
        - name: external-disk-provisioner
          image: registry.cn-hangzhou.aliyuncs.com/acs/csi-provisioner:v3.0.0-3f86569-aliyun
          args:
            - "--csi-address=$(ADDRESS)"
            - "--feature-gates=Topology=True"
            - "--volume-name-prefix=disk"
            - "--strict-topology=true"
            - "--timeout=150s"
            - "--leader-election=true"
            - "--extra-create-metadata=true"
            - "--retry-interval-start=500ms"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/csi-provisioner/diskplugin.csi.alibabacloud.com/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: disk-provisioner-dir
              mountPath: /var/lib/kubelet/csi-provisioner/diskplugin.csi.alibabacloud.com
        - name: external-disk-attacher
          image: registry.cn-hangzhou.aliyuncs.com/acs/csi-attacher:v2.1.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election=true"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/csi-provisioner/diskplugin.csi.alibabacloud.com/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: disk-provisioner-dir
              mountPath: /var/lib/kubelet/csi-provisioner/diskplugin.csi.alibabacloud.com
        - name: external-disk-resizer
          image: registry.cn-hangzhou.aliyuncs.com/acs/csi-resizer:v0.3.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/csi-provisioner/diskplugin.csi.alibabacloud.com/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: disk-provisioner-dir
              mountPath: /var/lib/kubelet/csi-provisioner/diskplugin.csi.alibabacloud.com
        - name: csi-provisioner
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: registry.cn-hangzhou.aliyuncs.com/acs/csi-plugin:v1.16.9.43-f36bb540-aliyun
          imagePullPolicy: "Always"
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--v=2"
            - "--driver=disk"
          env:
            - name: CSI_ENDPOINT
              value: unix://var/lib/kubelet/csi-provisioner/driverplugin.csi.alibabacloud.com-replace/csi.sock
            - name: MAX_VOLUMES_PERNODE
              value: "15"
            - name: ACCESS_KEY_ID
              value: "LTAIhqT3XXXXXXXX"
            - name: ACCESS_KEY_SECRET
              value: "IKL1FbnXR9RXXXXXXXXXXX"
            - name: SERVICE_TYPE
              value: "provisioner"
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          ports:
            - name: healthz
              containerPort: 11270
              protocol: TCP
          volumeMounts:
            - name: host-dev
              mountPath: /dev
              mountPropagation: "HostToContainer"
            - name: host-log
              mountPath: /var/log/
            - name: etc
              mountPath: /host/etc
            - name: disk-provisioner-dir
              mountPath: /var/lib/kubelet/csi-provisioner/diskplugin.csi.alibabacloud.com
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 100Mi
      volumes:
        - name: disk-provisioner-dir
          emptyDir: {}
        - name: host-log
          hostPath:
            path: /var/log/
        - name: host-dev
          hostPath:
            path: /dev
        - name: etc
          hostPath:
            path: /etc
```

- csi_connector.log
```
2021/12/17 10:31:41 OSS Connector Daemon Is Starting...
2021/12/17 10:31:41 Socket path is ready: /etc/csi-tool/connector.sock
2021/12/17 10:31:41 Daemon Started ...
```

- flexvolume_disk.log
```
time="2021-12-16T16:08:17+08:00" level=info msg="Plugin Init"
time="2021-12-16T16:08:17+08:00" level=info msg="Plugin Init"
time="2021-12-16T17:55:12+08:00" level=info msg="Plugin Init"
time="2021-12-16T17:55:32+08:00" level=info msg="Plugin Init"
time="2021-12-16T18:27:13+08:00" level=info msg="Plugin Init"
```

- plugin.csi.alibabacloud.com.log
```
time="2021-12-17T07:28:35Z" level=info msg="Starting csi-plugin Driver: diskplugin.csi.alibabacloud.com version: 1.0.0"
time="2021-12-17T07:34:38Z" level=info msg="Multi CSI Driver Name: disk, nodeID: , endPoints: unix://var/lib/kubelet/csi-plugins/driverplugin.csi.alibabacloud.com-replace/csi.sock"
time="2021-12-17T07:34:38Z" level=info msg="CSI Driver Branch: 'master', Version: 'v1.16.9.43-f36bb540-aliyun', Build time: '2020-10-12-21:54:17'\n"
time="2021-12-17T07:34:38Z" level=info msg="Create Stroage Path: /var/lib/kubelet/csi-plugins/diskplugin.csi.alibabacloud.com/controller"
time="2021-12-17T07:34:38Z" level=info msg="Create Stroage Path: /var/lib/kubelet/csi-plugins/diskplugin.csi.alibabacloud.com/node"
time="2021-12-17T07:34:38Z" level=info msg="CSI is running status."
time="2021-12-17T07:34:38Z" level=info msg="Metric listening on address: /healthz"
time="2021-12-17T07:34:39Z" level=info msg="Use node id : i-bp15rfcs9l0qyijyya0l"
time="2021-12-17T07:34:39Z" level=info msg="Get AK: use Local AK"
time="2021-12-17T07:34:39Z" level=info msg="Starting csi-plugin without sts"
time="2021-12-17T07:34:39Z" level=info msg="Not found configmap named as csi-plugin under kube-system, with error: configmaps \"csi-plugin\" not found"
time="2021-12-17T07:34:39Z" level=info msg="AD-Controller is disabled, CSI Disk Plugin running in kubelet mode."
time="2021-12-17T07:34:39Z" level=info msg="Describe node jishi-test and Set RunTimeClass to runc"
time="2021-12-17T07:34:39Z" level=info msg="Starting with GlobalConfigVar: region(cn-hangzhou), NodeID(i-bp15rfcs9l0qyijyya0l), ADControllerEnable(false), DiskTagEnable(false), DiskBdfEnable(false), MetricEnable(true), RunTimeClass(runc), DetachDisabled(false), DetachBeforeDelete(true)"
time="2021-12-17T07:34:39Z" level=info msg="NewNodeServer: MAX_VOLUMES_PERNODE is set to(not default): 15"
time="2021-12-17T07:34:39Z" level=info msg="Currently node is NOT VF model"
time="2021-12-17T07:34:39Z" level=info msg="Starting csi-plugin Driver: diskplugin.csi.alibabacloud.com version: 1.0.0"
```

- plugin.csi.alibabacloud.com.log
```
time="2021-12-17T07:34:38Z" level=info msg="Multi CSI Driver Name: disk, nodeID: , endPoints: unix://var/lib/kubelet/csi-plugins/driverplugin.csi.alibabacloud.com-replace/csi.sock"
time="2021-12-17T07:34:38Z" level=info msg="CSI Driver Branch: 'master', Version: 'v1.16.9.43-f36bb540-aliyun', Build time: '2020-10-12-21:54:17'\n"
time="2021-12-17T07:34:38Z" level=info msg="Create Stroage Path: /var/lib/kubelet/csi-plugins/diskplugin.csi.alibabacloud.com/controller"
time="2021-12-17T07:34:38Z" level=info msg="Create Stroage Path: /var/lib/kubelet/csi-plugins/diskplugin.csi.alibabacloud.com/node"
time="2021-12-17T07:34:38Z" level=info msg="CSI is running status."
time="2021-12-17T07:34:38Z" level=info msg="Metric listening on address: /healthz"
time="2021-12-17T07:34:39Z" level=info msg="Use node id : i-bp15rfcs9l0qyijyya0l"
time="2021-12-17T07:34:39Z" level=info msg="Get AK: use Local AK"
time="2021-12-17T07:34:39Z" level=info msg="Starting csi-plugin without sts"
time="2021-12-17T07:34:39Z" level=info msg="Not found configmap named as csi-plugin under kube-system, with error: configmaps \"csi-plugin\" not found"
time="2021-12-17T07:34:39Z" level=info msg="AD-Controller is disabled, CSI Disk Plugin running in kubelet mode."
time="2021-12-17T07:34:39Z" level=info msg="Describe node jishi-test and Set RunTimeClass to runc"
time="2021-12-17T07:34:39Z" level=info msg="Starting with GlobalConfigVar: region(cn-hangzhou), NodeID(i-bp15rfcs9l0qyijyya0l), ADControllerEnable(false), DiskTagEnable(false), DiskBdfEnable(false), MetricEnable(true), RunTimeClass(runc), DetachDisabled(false), DetachBeforeDelete(true)"
time="2021-12-17T07:34:39Z" level=info msg="NewNodeServer: MAX_VOLUMES_PERNODE is set to(not default): 15"
time="2021-12-17T07:34:39Z" level=info msg="Currently node is NOT VF model"
time="2021-12-17T07:34:39Z" level=info msg="Starting csi-plugin Driver: diskplugin.csi.alibabacloud.com version: 1.0.0"
```

- kubectl get pv
```
NAME                     CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                   STORAGECLASS                   REASON   AGE
d-bp1gg7bf8py8d1wjj7k9   20Gi       RWO            Retain           Bound    default/data-apisix-1639713714-etcd-0   alicloud-disk-ssd-hangzhou-g            20h
```

- kubectl get pvc
```
NAME                            STATUS    VOLUME                   CAPACITY   ACCESS MODES   STORAGECLASS                   AGE
data-apisix-1639713714-etcd-0   Bound     d-bp1gg7bf8py8d1wjj7k9   20Gi       RWO            alicloud-disk-ssd-hangzhou-g   43h
```

-  kubectl describe pod apisix-1639713714-etcd-0
```
Name:           apisix-1639713714-etcd-0
Namespace:      default
Priority:       0
Node:           izbp1eaqxmgbuqsaaokrxnz/172.16.219.236
Start Time:     Sun, 19 Dec 2021 18:37:03 +0800
Labels:         app.kubernetes.io/instance=apisix-1639713714
                app.kubernetes.io/managed-by=Helm
                app.kubernetes.io/name=etcd
                controller-revision-hash=apisix-1639713714-etcd-65dd648984
                helm.sh/chart=etcd-6.2.6
                statefulset.kubernetes.io/pod-name=apisix-1639713714-etcd-0
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  StatefulSet/apisix-1639713714-etcd
Init Containers:
  volume-permissions:
    Container ID:
    Image:         docker.io/bitnami/bitnami-shell:10-debian-10-r92
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/bash
      -ec
      chown -R 1001:1001 /bitnami/etcd

    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /bitnami/etcd from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-qb2bl (ro)
Containers:
  etcd:
    Container ID:
    Image:          docker.io/bitnami/etcd:3.4.16-debian-10-r14
    Image ID:
    Ports:          2379/TCP, 2380/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Liveness:       exec [/opt/bitnami/scripts/etcd/healthcheck.sh] delay=60s timeout=5s period=30s #success=1 #failure=5
    Readiness:      exec [/opt/bitnami/scripts/etcd/healthcheck.sh] delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:
      BITNAMI_DEBUG:                     false
      MY_POD_IP:                          (v1:status.podIP)
      MY_POD_NAME:                       apisix-1639713714-etcd-0 (v1:metadata.name)
      ETCDCTL_API:                       3
      ETCD_ON_K8S:                       yes
      ETCD_START_FROM_SNAPSHOT:          no
      ETCD_DISASTER_RECOVERY:            no
      ETCD_NAME:                         $(MY_POD_NAME)
      ETCD_DATA_DIR:                     /bitnami/etcd/data
      ETCD_LOG_LEVEL:                    info
      ALLOW_NONE_AUTHENTICATION:         yes
      ETCD_ADVERTISE_CLIENT_URLS:        http://$(MY_POD_NAME).apisix-1639713714-etcd-headless.default.svc.cluster.local:2379
      ETCD_LISTEN_CLIENT_URLS:           http://0.0.0.0:2379
      ETCD_INITIAL_ADVERTISE_PEER_URLS:  http://$(MY_POD_NAME).apisix-1639713714-etcd-headless.default.svc.cluster.local:2380
      ETCD_LISTEN_PEER_URLS:             http://0.0.0.0:2380
      ETCD_INITIAL_CLUSTER_TOKEN:        etcd-cluster-k8s
      ETCD_INITIAL_CLUSTER_STATE:        existing
      ETCD_INITIAL_CLUSTER:              apisix-1639713714-etcd-0=http://apisix-1639713714-etcd-0.apisix-1639713714-etcd-headless.default.svc.cluster.local:2380,apisix-1639713714-etcd-1=http://apisix-1639713714-etcd-1.apisix-1639713714-etcd-headless.default.svc.cluster.local:2380,apisix-1639713714-etcd-2=http://apisix-1639713714-etcd-2.apisix-1639713714-etcd-headless.default.svc.cluster.local:2380
      ETCD_CLUSTER_DOMAIN:               apisix-1639713714-etcd-headless.default.svc.cluster.local
    Mounts:
      /bitnami/etcd from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-qb2bl (ro)
Conditions:
  Type              Status
  Initialized       False
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-apisix-1639713714-etcd-0
    ReadOnly:   false
  kube-api-access-qb2bl:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason              Age                    From                     Message
  ----     ------              ----                   ----                     -------
  Warning  FailedMount         11m (x303 over 15h)    kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data kube-api-access-qb2bl]: timed out waiting for the condition
  Warning  FailedAttachVolume  5m26s (x229 over 15h)  attachdetach-controller  AttachVolume.Attach failed for volume "d-bp1gg7bf8py8d1wjj7k9" : Attach timeout for volume d-bp1gg7bf8py8d1wjj7k9
  Warning  FailedMount         4m15s (x96 over 15h)   kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[kube-api-access-qb2bl data]: timed out waiting for the condition
```
