### ISSUE TITLE
Unable to access OSS on on-premise K3s server

### ISSUE THREAD

**Issue by aqu-anth** [kubernetes-sigs/alibaba-cloud-csi-driver#600]
When I try to access /data folder which is mounted to OSS bucket, it throwe the below error.
Error: Transport endpoint is not connected

#### Environment:
- Kubernetes version (use `kubectl version`): Major:"1", Minor:"22", GitVersion:"v1.22.6+k3s1"
- OS (e.g: `cat /etc/os-release`): CentOS-7
#### Deployment:
- csi-plugin.yaml:
```
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: ossplugin.csi.alibabacloud.com
spec:
  attachRequired: false
  podInfoOnMount: true
---
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: nasplugin.csi.alibabacloud.com
spec:
  attachRequired: false
  podInfoOnMount: true
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-plugin
  template:
    metadata:
      labels:
        app: csi-plugin
    spec:
      tolerations:
        - operator: Exists
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
      nodeSelector:
        beta.kubernetes.io/os: linux
      serviceAccount: csi-admin
      priorityClassName: system-node-critical
      hostNetwork: true
      hostPID: true
      containers:
        - name: oss-driver-registrar
          image: registry.cn-hangzhou.aliyuncs.com/acs/csi-node-driver-registrar:v1.2.0
          imagePullPolicy: Always
          args:
            - "--v=5"
            - "--csi-address=/var/lib/kubelet/csi-plugins/ossplugin.csi.alibabacloud.com/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/csi-plugins/ossplugin.csi.alibabacloud.com/csi.sock"
          volumeMounts:
            - name: kubelet-dir
              mountPath: /var/lib/kubelet/
            - name: registration-dir
              mountPath: /registration
        - name: nas-driver-registrar
          image: registry.cn-hangzhou.aliyuncs.com/acs/csi-node-driver-registrar:v1.2.0
          imagePullPolicy: Always
          args:
            - "--v=5"
            - "--csi-address=/var/lib/kubelet/csi-plugins/nasplugin.csi.alibabacloud.com/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/csi-plugins/nasplugin.csi.alibabacloud.com/csi.sock"
          volumeMounts:
            - name: kubelet-dir
              mountPath: /var/lib/kubelet/
            - name: registration-dir
              mountPath: /registration
        - name: csi-plugin
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: registry.cn-hangzhou.aliyuncs.com/acs/csi-plugin:v1.18.8.47-906bd535-aliyun
          imagePullPolicy: "Always"
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--v=2"
            - "--driver=oss,nas"
            - "--nodeid=$(KUBE_NODE_NAME)"
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://var/lib/kubelet/csi-plugins/driverplugin.csi.alibabacloud.com-replace/csi.sock
            - name: MAX_VOLUMES_PERNODE
              value: "15"
            - name: SERVICE_TYPE
              value: "plugin"
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          ports:
            - name: healthz
              containerPort: 11260
              protocol: TCP
          volumeMounts:
            - name: kubelet-dir
              mountPath: /var/lib/kubelet/
              mountPropagation: "Bidirectional"
            - name: etc
              mountPath: /host/etc
            - name: host-log
              mountPath: /var/log/
            - name: ossconnectordir
              mountPath: /host/usr/
            - name: container-dir
              mountPath: /var/lib/container
              mountPropagation: "Bidirectional"
            - name: host-dev
              mountPath: /dev
              mountPropagation: "HostToContainer"
      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: DirectoryOrCreate
        - name: container-dir
          hostPath:
            path: /var/lib/container
            type: DirectoryOrCreate
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: host-dev
          hostPath:
            path: /dev
        - name: host-log
          hostPath:
            path: /var/log/
        - name: etc
          hostPath:
            path: /etc
        - name: ossconnectordir
          hostPath:
            path: /usr/
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate
```

- deployment.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nas
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /data
            name: ossdir
      volumes:
        - name: ossdir
          persistentVolumeClaim:
            claimName: oss-log-bucket-pvc

```

**Comment by mowangdk** [comment]
> When I try to access /data folder which is mounted to OSS bucket, it throwe the below error. Error: Transport endpoint is not connected
> 
> #### Environment:
> * Kubernetes version (use `kubectl version`): Major:"1", Minor:"22", GitVersion:"v1.22.6+k3s1"
> * OS (e.g: `cat /etc/os-release`): CentOS-7
> 
> #### Deployment:
> * csi-plugin.yaml:
> 
> ```
> apiVersion: storage.k8s.io/v1beta1
> kind: CSIDriver
> metadata:
>   name: ossplugin.csi.alibabacloud.com
> spec:
>   attachRequired: false
>   podInfoOnMount: true
> ---
> apiVersion: storage.k8s.io/v1beta1
> kind: CSIDriver
> metadata:
>   name: nasplugin.csi.alibabacloud.com
> spec:
>   attachRequired: false
>   podInfoOnMount: true
> ---
> kind: DaemonSet
> apiVersion: apps/v1
> metadata:
>   name: csi-plugin
>   namespace: kube-system
> spec:
>   selector:
>     matchLabels:
>       app: csi-plugin
>   template:
>     metadata:
>       labels:
>         app: csi-plugin
>     spec:
>       tolerations:
>         - operator: Exists
>       affinity:
>         nodeAffinity:
>           requiredDuringSchedulingIgnoredDuringExecution:
>             nodeSelectorTerms:
>             - matchExpressions:
>               - key: type
>                 operator: NotIn
>                 values:
>                 - virtual-kubelet
>       nodeSelector:
>         beta.kubernetes.io/os: linux
>       serviceAccount: csi-admin
>       priorityClassName: system-node-critical
>       hostNetwork: true
>       hostPID: true
>       containers:
>         - name: oss-driver-registrar
>           image: registry.cn-hangzhou.aliyuncs.com/acs/csi-node-driver-registrar:v1.2.0
>           imagePullPolicy: Always
>           args:
>             - "--v=5"
>             - "--csi-address=/var/lib/kubelet/csi-plugins/ossplugin.csi.alibabacloud.com/csi.sock"
>             - "--kubelet-registration-path=/var/lib/kubelet/csi-plugins/ossplugin.csi.alibabacloud.com/csi.sock"
>           volumeMounts:
>             - name: kubelet-dir
>               mountPath: /var/lib/kubelet/
>             - name: registration-dir
>               mountPath: /registration
>         - name: nas-driver-registrar
>           image: registry.cn-hangzhou.aliyuncs.com/acs/csi-node-driver-registrar:v1.2.0
>           imagePullPolicy: Always
>           args:
>             - "--v=5"
>             - "--csi-address=/var/lib/kubelet/csi-plugins/nasplugin.csi.alibabacloud.com/csi.sock"
>             - "--kubelet-registration-path=/var/lib/kubelet/csi-plugins/nasplugin.csi.alibabacloud.com/csi.sock"
>           volumeMounts:
>             - name: kubelet-dir
>               mountPath: /var/lib/kubelet/
>             - name: registration-dir
>               mountPath: /registration
>         - name: csi-plugin
>           securityContext:
>             privileged: true
>             capabilities:
>               add: ["SYS_ADMIN"]
>             allowPrivilegeEscalation: true
>           image: registry.cn-hangzhou.aliyuncs.com/acs/csi-plugin:v1.18.8.47-906bd535-aliyun
>           imagePullPolicy: "Always"
>           args:
>             - "--endpoint=$(CSI_ENDPOINT)"
>             - "--v=2"
>             - "--driver=oss,nas"
>             - "--nodeid=$(KUBE_NODE_NAME)"
>           env:
>             - name: KUBE_NODE_NAME
>               valueFrom:
>                 fieldRef:
>                   apiVersion: v1
>                   fieldPath: spec.nodeName
>             - name: CSI_ENDPOINT
>               value: unix://var/lib/kubelet/csi-plugins/driverplugin.csi.alibabacloud.com-replace/csi.sock
>             - name: MAX_VOLUMES_PERNODE
>               value: "15"
>             - name: SERVICE_TYPE
>               value: "plugin"
>           livenessProbe:
>             httpGet:
>               path: /healthz
>               port: healthz
>               scheme: HTTP
>             initialDelaySeconds: 10
>             periodSeconds: 30
>             timeoutSeconds: 5
>             failureThreshold: 5
>           ports:
>             - name: healthz
>               containerPort: 11260
>               protocol: TCP
>           volumeMounts:
>             - name: kubelet-dir
>               mountPath: /var/lib/kubelet/
>               mountPropagation: "Bidirectional"
>             - name: etc
>               mountPath: /host/etc
>             - name: host-log
>               mountPath: /var/log/
>             - name: ossconnectordir
>               mountPath: /host/usr/
>             - name: container-dir
>               mountPath: /var/lib/container
>               mountPropagation: "Bidirectional"
>             - name: host-dev
>               mountPath: /dev
>               mountPropagation: "HostToContainer"
>       volumes:
>         - name: registration-dir
>           hostPath:
>             path: /var/lib/kubelet/plugins_registry
>             type: DirectoryOrCreate
>         - name: container-dir
>           hostPath:
>             path: /var/lib/container
>             type: DirectoryOrCreate
>         - name: kubelet-dir
>           hostPath:
>             path: /var/lib/kubelet
>             type: Directory
>         - name: host-dev
>           hostPath:
>             path: /dev
>         - name: host-log
>           hostPath:
>             path: /var/log/
>         - name: etc
>           hostPath:
>             path: /etc
>         - name: ossconnectordir
>           hostPath:
>             path: /usr/
>   updateStrategy:
>     rollingUpdate:
>       maxUnavailable: 10%
>     type: RollingUpdate
> ```
> 
> * deployment.yaml:
> 
> ```
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: deployment-nas
>   labels:
>     app: nginx
> spec:
>   selector:
>     matchLabels:
>       app: nginx
>   template:
>     metadata:
>       labels:
>         app: nginx
>     spec:
>       containers:
>       - name: nginx
>         image: nginx:1.7.9
>         ports:
>         - containerPort: 80
>         volumeMounts:
>           - mountPath: /data
>             name: ossdir
>       volumes:
>         - name: ossdir
>           persistentVolumeClaim:
>             claimName: oss-log-bucket-pvc
> ```

pls use csi-provisioner.yaml & csi-plugin.yaml under deploy/ack to redeploy csi components.

**Comment by aqu-anth** [comment]
After I redeploy the csi-plugin.yaml using the yaml file under deploy/ack, the csi-plugin fails to start.
```
level=fatal msg="Error happens to get node document: Get \"http://100.100.100.200/latest/dynamic/instance-identity/document\": read tcp 100.100.100.200:80: read: connection reset by peer"

```

**Comment by mowangdk** [comment]
> Error happens to get node document:

you didn't use disk right? remove disk driver from yamls.
![image](https://user-images.githubusercontent.com/9926112/153112047-913d1162-74b0-4f61-96ed-b19c785203f1.png)
![image](https://user-images.githubusercontent.com/9926112/153112083-3a1afba7-c611-4c4d-bc54-8c33ff84b513.png)

**Comment by aqu-anth** [comment]
I tried to redeploy all csi components on K3s and I created a testing pod with volume mounted to my oss pv. When I ran LS command, it showed the below error. `ls: reading directory .: Software caused connection abort`

**Comment by mowangdk** [comment]
which pod is the ls command run at?

**Comment by aqu-anth** [comment]
I create a Nginx pod to test OSS connection. 

deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-oss
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
          - name: oss-pvc
            mountPath: "/data"
      volumes:
        - name: oss-pvc
          persistentVolumeClaim:
            claimName: oss-pvc
```
pv.yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: oss-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: ossplugin.csi.alibabacloud.com
    volumeHandle: oss-pv
    nodePublishSecretRef:
      name: oss-secrets
    volumeAttributes:
      bucket: // bucket name
      url:  // endpoint
      otherOpts: "-o max_stat_cache_size=0 -o allow_other"
```

pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oss-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: oss-pv
  storageClassName: ''
```
