### ISSUE TITLE
otherOpts never worked

### ISSUE THREAD

**Issue by ericjee** [kubernetes-sigs/alibaba-cloud-csi-driver#637]
#### What happened:
这个opts看上去是不工作的，我建了一块oss静态卷指定`max_stat_cache_size=0`并绑定后，进到容器里执行`ls`并`watch`，在我控制台上传`object`至`bucket`后，容器内目录永远不会更新，`ls`看不见新的object，另外`allow-other`也是不工作的，我的容器切到3000 user，`cd`目录报无权限。

#### How to reproduce it (as minimally and precisely as possible):
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-oss
  labels:
    alicloud-pvname: pv-oss
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: oss
  csi:
    driver: "ossplugin.csi.alibabacloud.com"
    volumeHandle: pv-oss
    volumeAttributes:
      bucket: ""
      url: "oss-cn-shanghai-internal.aliyuncs.com"
      path: "/public"
      akId: ""
      akSecret: ""
      otherOpts: "-o max_stat_cache_size=0"
```
#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
