### ISSUE TITLE
Need info: Supportable disk types list with their supportable Regions

### ISSUE THREAD

**Issue by ropatil010** [kubernetes-sigs/alibaba-cloud-csi-driver#774]
Hi, 
I am looking for which are supportable disk types with their respective regions? 
Example:
    Disktypes: cloud_essd(us-west-1,us-east-1), cloud_ssd(us-east-1, us-west-1), cloud_efficiency, cloud, san_ssd, san_efficiency
    Regions: cloud_ssd supportable regions are US-Virginia, UK-London, US-SliconValley, Germany. 
    
Similary can we get bit more info for all disk types and their supportable Regions?

**Comment by ropatil010** [comment]
Hi @mowangdk, Any updates you have?

**Comment by mowangdk** [comment]
@ropatil010 Sorry for the late reply, but this information is not transparent to the public as it relates to inventory information, it is recommended to use the following storageclass to be compatible with this situation


```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alicloud-disk-topology-alltype
parameters:
  type: cloud_essd,cloud_ssd,cloud_efficiency
provisioner: diskplugin.csi.alibabacloud.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
